name: Deploy Backend to Azure Functions

on:
  push:
    paths:
      - 'backend/**'
      - 'pyproject.toml'
      - '.github/workflows/backend-deploy.yml'
      - '.python-version'
  pull_request:
    paths:
      - 'backend/**'
      - 'pyproject.toml'
      - '.github/workflows/backend-deploy.yml'
      - '.python-version'


env:
  AZURE_FUNCTIONAPP_NAME: 'textfocals'   # set this to your function app name on Azure
  AZURE_FUNCTIONAPP_PACKAGE_PATH: './backend'       # set this to the path to your function app project, defaults to the repository root




jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: 'Checkout GitHub Action'
      uses: actions/checkout@v4

    - name: Install uv
      uses: astral-sh/setup-uv@v3

    - name: "Set up Python"
      uses: actions/setup-python@v5
      with:
        python-version-file: ".python-version"

    - name: Install dependencies
      run: |
        uv sync && uv pip freeze > backend/requirements.txt


    - name: 'Resolve Project Dependencies Using Pip'
      shell: bash
      run: |
        pushd './${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}'
        python -m pip install --upgrade pip
        pip install -r requirements.txt --target=".python_packages/lib/site-packages"
        popd

    - name: 'Run Azure Functions Action'
      uses: Azure/functions-action@v1
      id: fa
      with:
        app-name: ${{ env.AZURE_FUNCTIONAPP_NAME }}
        package: ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}
        publish-profile: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE }} 
        # How to set up the Azure publish profile:
        # Go to your Function App in Azure Portal
        # Click "Overview" → "Get publish profile"
        # Copy the contents of the downloaded file and add it to your GitHub repository secrets as AZURE_FUNCTIONAPP_PUBLISH_PROFILE
        respect-funcignore: true


