name: Backend Tests

on:
  push:
    paths:
      - 'backend/**'
      - 'pyproject.toml'
      - '.github/workflows/backend-tests.yml'
  pull_request:
    paths:
      - 'backend/**'
      - 'pyproject.toml'
      - '.github/workflows/backend-tests.yml'


env:
  AZURE_FUNCTIONAPP_NAME: 'textfocals-test'   # set this to your function app name on Azure
  AZURE_FUNCTIONAPP_PACKAGE_PATH: './backend'       # set this to the path to your function app project, defaults to the repository root
  PYTHON_VERSION: '3.9'                     # set this to the python version to use (e.g. '3.6', '3.7', '3.8')




jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend

    steps:
    - name: 'Checkout GitHub Action'
      uses: actions/checkout@v4

    - name: Install uv
      uses: astral-sh/setup-uv@v3

    # - name: "Set up Python"
    #   uses: actions/setup-python@v5
    #   with:
    #     python-version: ${{ env.PYTHON_VERSION }}

    - name: Install dependencies
      run: |
        uv pip freeze > requirements.txt


    - name: 'Resolve Project Dependencies Using Pip'
      shell: bash
      run: |
        pushd './${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}'
        python -m pip install --upgrade pip
        pip install -r requirements.txt --target=".python_packages/lib/site-packages"
        popd

    - name: 'Run Azure Functions Action'
      uses: Azure/functions-action@v1
      id: fa
      with:
        app-name: ${{ env.AZURE_FUNCTIONAPP_NAME }}
        package: ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}
        publish-profile: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE }} 
        # How to set up the Azure publish profile:
        # Go to your Function App in Azure Portal
        # Click "Overview" → "Get publish profile"
        # Copy the contents of the downloaded file and add it to your GitHub repository secrets as AZURE_FUNCTIONAPP_PUBLISH_PROFILE
        scm-do-build-during-deployment: true
        enable-oryx-build: true




